# Generated by Django 2.1.15 on 2020-02-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinstance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinstance',
            name='board_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinstance',
            name='comment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinstance',
            name='instance_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinstance',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinstance',
            name='space_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinstance',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kinstance',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
