version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "7000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=knowledge_database
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=knowledge_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
    - 5432:5432