version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=knowledge_database
      - DB_USER=postgres
      - DB_PASS=password
      - DB_HOST_AUDIT=db
      - DB_NAME_AUDIT=knowledge_database
      - DB_USER_AUDIT=postgres
      - DB_PASS_AUDIT=password
      - DB_PORT_AUDIT=5440
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=knowledge_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
    - 5432:5432
  
  audit-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=audit_knowledge_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
    - 5440:5432