# Generated by Django 2.2 on 2021-05-03 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paConfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.UUIDField(default=uuid.uuid4)),
                ('forecast', models.BooleanField(default=False)),
                ('reforecast', models.BooleanField(default=False)),
                ('portfolioView', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.UUIDField(default=uuid.uuid4)),
                ('ctms_matrix', models.BooleanField(default=False)),
                ('design_optimization_matrix', models.BooleanField(default=False)),
                ('cost_matrix', models.BooleanField(default=False)),
            ],
        ),
    ]
