# Generated by Django 2.1.15 on 2020-02-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('task', '0002_auto_20200224_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_belongs_to_board', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_belongs_to_project', to='project.Project'),
        ),
    ]
